name: flutter_architecture_mvvm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_localization: ^0.1.10
  
  # For Networking
  dio: ^5.0.2
  riverpod: ^2.3.2
  hooks_riverpod: ^2.3.2
  flutter_riverpod: ^2.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:
  uses-material-design: true
  generate: true

