name: architecture_mvvm_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.0.1
  freezed_annotation: ^2.2.0
  
  dio: ^5.0.2 
  #dio_http_cache: ^0.2.3

  flutter_riverpod: ^2.3.2
  hooks_riverpod: ^2.3.2
  mmkv: ^1.2.16
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
 
  freezed: ^2.3.2
  
  build_runner: ^2.3.3
  json_serializable: ^6.1.1

dependency_overrides:
  # for dio_http_cache
  #json_serializable: ^3.0.0
   # for dio_http_cache
  #json_annotation: ^3.0.0

flutter:

  uses-material-design: true
